;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AI",DevComment="")
+GameplayTagList=(Tag="AI.Event",DevComment="")
+GameplayTagList=(Tag="AI.Event.AdditionalAction",DevComment="")
+GameplayTagList=(Tag="AI.Event.Combat",DevComment="")
+GameplayTagList=(Tag="AI.Event.Death",DevComment="")
+GameplayTagList=(Tag="AI.Event.Idle",DevComment="")
+GameplayTagList=(Tag="AI.Event.Initialization",DevComment="")
+GameplayTagList=(Tag="AI.Event.Reaction",DevComment="")
+GameplayTagList=(Tag="AI.State.AdditionalAction",DevComment="")
+GameplayTagList=(Tag="AI.State.Combat",DevComment="")
+GameplayTagList=(Tag="AI.State.Death",DevComment="")
+GameplayTagList=(Tag="AI.State.Idle",DevComment="")
+GameplayTagList=(Tag="AI.State.Initialization",DevComment="")
+GameplayTagList=(Tag="AI.State.Reaction",DevComment="")
+GameplayTagList=(Tag="UI.Slot",DevComment="")
+GameplayTagList=(Tag="UI.Slot.Crosshair",DevComment="")
+GameplayTagList=(Tag="UI.Slot.Interact",DevComment="")
+GameplayTagList=(Tag="UI.Slot.Weapon",DevComment="")

